baseurl = "https://goodroot.ca"
languageCode = "en-us"
title = "Goodroot"
theme = "hugo-classic"
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true

footnotereturnlinkcontents = "â†©"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[params]
    description = "An introduction to Goodroot."
    footer = "Be Excellent to Each Other | [GitHub](https://github.com/goodroot) | [keybase](https://keybase.io/goodroot) | public@goodroot.ca"
